--
-- Created by IntelliJ IDEA.
-- User: denny
-- Date: 2/1/2017
-- Time: 10:02 PM
-- To change this template use File | Settings | File Templates.
--

FormCreate(varFormNameMapMainOlderion)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, picBtnMapBack)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapDirnado)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapGrandshelt)
FormAddCriteria2Do(varCriteriaExists, picBtnMapVortex)
FormAddCriteria2Do(varCriteriaExists, picBtnMapOlderion)

FormCreate(varFormNameMapMainDirnadoOlderion)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, picBtnMapBack)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapGrandshelt)
FormAddCriteria2Do(varCriteriaExists, picBtnMapVortex)
FormAddCriteria2Do(varCriteriaExists, picBtnMapDirnado)
FormAddCriteria2Do(varCriteriaExists, picBtnMapOlderion)

FormCreate(varFormNameMapMainDirnado)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, picBtnMapBack)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapGrandshelt)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapOlderion)
FormAddCriteria2Do(varCriteriaExists, picBtnMapVortex)
FormAddCriteria2Do(varCriteriaExists, picBtnMapDirnado)

FormCreate(varFormNameMapMainDirnadoGrandshelt)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, picBtnMapBack)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapOlderion)
FormAddCriteria2Do(varCriteriaExists, picBtnMapVortex)
FormAddCriteria2Do(varCriteriaExists, picBtnMapDirnado)
FormAddCriteria2Do(varCriteriaExists, picBtnMapGrandshelt)

FormCreate(varFormNameMapMainGrandshelt)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, picBtnMapBack)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapOlderion)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapDirnado)
FormAddCriteria2Do(varCriteriaExists, picBtnMapVortex)
FormAddCriteria2Do(varCriteriaExists, picBtnMapGrandshelt)



FormCreate(varFormNameMapGrandshelt)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapGrandsheltTop)

FormCreate(varFormNameMapGrandGrandArdOrdolPort)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapGrandGrandIslesTop)
FormAddCriteria2Do(varCriteriaExists, picBtnMapGrandGrandIslesOrdolPort)
FormAddCriteria2Do(varCriteriaRegionNotExists)
FormAddCriteria2Var(picBtnMapGrandGrandIslesOrdolPort)
FormAddCriteria2Var(Region(locMapTownCenterX1, locMapTownCenterY1, locMapTownCenterW1, locMapTownCenterY1))

FormCreate(varFormNameMapGrandGrandCtrOrdolPort)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapGrandGrandIslesTop)
FormAddCriteria2Do(varCriteriaExists, picBtnMapGrandGrandIslesOrdolPort)
FormAddCriteria2Do(varCriteriaRegionExists)
FormAddCriteria2Var(picBtnMapGrandGrandIslesOrdolPort)
FormAddCriteria2Var(Region(locMapTownCenterX1, locMapTownCenterY1, locMapTownCenterW1, locMapTownCenterY1))

FormCreate(varFormNameMapGrandGrandArdEarthShrine)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapGrandGrandIslesTop)
FormAddCriteria2Do(varCriteriaExists, picBtnMapGrandGrandIslesEarthShrine)
FormAddCriteria2Do(varCriteriaRegionNotExists)
FormAddCriteria2Var(picBtnMapGrandGrandIslesEarthShrine)
FormAddCriteria2Var(Region(locMapTownCenterX1, locMapTownCenterY1, locMapTownCenterW1, locMapTownCenterY1))

FormCreate(varFormNameMapGrandGrandCtrEarthShrine)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapGrandGrandIslesTop)
FormAddCriteria2Do(varCriteriaExists, picBtnMapGrandGrandIslesEarthShrine)
FormAddCriteria2Do(varCriteriaRegionExists)
FormAddCriteria2Var(picBtnMapGrandGrandIslesEarthShrine)
FormAddCriteria2Var(Region(locMapTownCenterX1, locMapTownCenterY1, locMapTownCenterW1, locMapTownCenterY1))

FormCreate(varFormNameMapGrandGrandNoEarthOrdol)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapGrandGrandIslesTop)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapGrandGrandIslesEarthShrine)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMapGrandGrandIslesOrdolPort)

FormCreate(varFormNameMapDirnado)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapDirnadoTop)

FormCreate(varFormNameMapOlderion)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapOlderionTop)

FormCreate(varFormNameMapOlderionCtrAquaticCove)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapOlderionTop)
FormAddCriteria2Do(varCriteriaExists, picBtnMapOlderionAquaticCove)
FormAddCriteria2Do(varCriteriaRegionExists)
FormAddCriteria2Var(picBtnMapOlderionAquaticCove)
FormAddCriteria2Var(Region(locMapTownCenterX1, locMapTownCenterY1, locMapTownCenterW1, locMapTownCenterY1))

FormCreate(varFormNameMapCompanionUpdate)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMapCompanionUpdateMid)


