--
-- Created by IntelliJ IDEA.
-- User: denny
-- Date: 3/28/2017
-- Time: 11:00 PM
-- To change this template use File | Settings | File Templates.
--

--  ##  Magic  ##
--picBtnBattleMagicCuraja1    --  LEFT SIDE
--picBtnBattleMagicCuraja2    --  RIGHT SIDE

picBtnBattleLimitBurst                          = folderffbeimage.."magic/btn_battle_limit_burst.png"



picBtnBattleAbilityAffectionateAura1            = folderffbeimage.."magic/btn_battle_ability_affectionate_aura1.png"
picBtnBattleAbilityArchadianLight1              = folderffbeimage.."magic/btn_battle_ability_archadian_light1.png"
picBtnBattleAbilityArmorBreak2                  = folderffbeimage.."magic/btn_battle_ability_armor_break2.png"
picBtnBattleAbilityArmorEraser1                 = folderffbeimage.."magic/btn_battle_ability_armor_eraser1.png"
picBtnBattleAbilityArmsEraser2                  = folderffbeimage.."magic/btn_battle_ability_arms_eraser2.png"
picBtnBattleAbilityAssaultOrder1                = folderffbeimage.."magic/btn_battle_ability_assault_order1.png"
picBtnBattleAbilityAssaultOrder2                = folderffbeimage.."magic/btn_battle_ability_assault_order2.png"
picBtnBattleAbilityAssaultStrike2               = folderffbeimage.."magic/btn_battle_ability_assault_strike2.png"
picBtnBattleAbilityAttackSong2                  = folderffbeimage.."magic/btn_battle_ability_attack_song2.png"
picBtnBattleAbilityBlackHole2                   = folderffbeimage.."magic/btn_battle_ability_black_hole2.png"
picBtnBattleAbilityBladeblitz1                  = folderffbeimage.."magic/btn_battle_ability_bladeblitz1.png"
picBtnBattleAbilityBladeblitz2                  = folderffbeimage.."magic/btn_battle_ability_bladeblitz2.png"
picBtnBattleAbilityBlizzardFlask1               = folderffbeimage.."magic/btn_battle_ability_blizzard_flask1.png"
picBtnBattleAbilityBoost                        = folderffbeimage.."magic/btn_battle_ability_boost.png"
picBtnBattleAbilityBravePresence1  		        = folderffbeimage.."magic/btn_battle_ability_brave_presence1.png"
picBtnBattleAbilityBringItOn2      		        = folderffbeimage.."magic/btn_battle_ability_bring_it_on2.png"
picBtnBattleAbilityBuildEarth2     		        = folderffbeimage.."magic/btn_battle_ability_build_earth2.png"
picBtnBattleAbilityCallToAttack1                = folderffbeimage.."magic/btn_battle_ability_call_to_attack1.png"
picBtnBattleAbilityCallToAttack2                = folderffbeimage.."magic/btn_battle_ability_call_to_attack2.png"
picBtnBattleAbilityCallToDefend2                = folderffbeimage.."magic/btn_battle_ability_call_to_defend2.png"
picBtnBattleAbilityCallToMagic1                 = folderffbeimage.."magic/btn_battle_ability_call_to_magic1.png"
picBtnBattleAbilityCallToSpirit2                = folderffbeimage.."magic/btn_battle_ability_call_to_spirit2.png"
picBtnBattleAbilityCelestialLight2              = folderffbeimage.."magic/btn_battle_ability_celestial_light2.png"
picBtnBattleAbilityChaosWave2                   = folderffbeimage.."magic/btn_battle_ability_chaos_wave2.png"
picBtnBattleAbilityCleansingStrike2             = folderffbeimage.."magic/btn_battle_ability_cleansing_strike2.png"
picBtnBattleAbilityCrushWeapon2                 = folderffbeimage.."magic/btn_battle_ability_crush_weapon2.png"
picBtnBattleAbilityCursedCard1                  = folderffbeimage.."magic/btn_battle_ability_cursed_card1.png"
picBtnBattleAbilityCursedCard2                  = folderffbeimage.."magic/btn_battle_ability_cursed_card2.png"
picBtnBattleAbilityDanceTune2                   = folderffbeimage.."magic/btn_battle_ability_dance_tune2.png"
picBtnBattleAbilityDarkNebula1                  = folderffbeimage.."magic/btn_battle_ability_dark_nebula1.png"
picBtnBattleAbilityDarkNebula2                  = folderffbeimage.."magic/btn_battle_ability_dark_nebula2.png"
picBtnBattleAbilityDestiny1           		    = folderffbeimage.."magic/btn_battle_ability_destiny1.png"
picBtnBattleAbilityDivineRuination1   		    = folderffbeimage.."magic/btn_battle_ability_divine_ruination1.png"
picBtnBattleAbilityDivingStrike2      		    = folderffbeimage.."magic/btn_battle_ability_diving_strike2.png"
picBtnBattleAbilityDualcast1                    = folderffbeimage.."magic/btn_battle_ability_dualcast1.png"
picBtnBattleAbilityDualcast2                    = folderffbeimage.."magic/btn_battle_ability_dualcast2.png"
picBtnBattleAbilityElementlash1                 = folderffbeimage.."magic/btn_battle_ability_elementlash1.png"
picBtnBattleAbilityFinBriar                     = folderffbeimage.."magic/btn_battle_ability_fin_briar.png"
picBtnBattleAbilityFlameGuard1                  = folderffbeimage.."magic/btn_battle_ability_flame_guard1.png"
picBtnBattleAbilityFlameGuard2                  = folderffbeimage.."magic/btn_battle_ability_flame_guard2.png"
picBtnBattleAbilityFlashGrenade1                = folderffbeimage.."magic/btn_battle_ability_flash_grenade1.png"
picBtnBattleAbilityFlashOfBrilliance            = folderffbeimage.."magic/btn_battle_ability_flash_of_brilliance.png"
picBtnBattleAbilityFrozenGuard2                 = folderffbeimage.."magic/btn_battle_ability_frozen_guard2.png"
picBtnBattleAbilityFullBreak1                   = folderffbeimage.."magic/btn_battle_ability_full_break1.png"
picBtnBattleAbilityFullBreak2                   = folderffbeimage.."magic/btn_battle_ability_full_break2.png"
picBtnBattleAbilityGaleBlast1        		    = folderffbeimage.."magic/btn_battle_ability_gale_blast1.png"
picBtnBattleAbilityGlacialWave1    		        = folderffbeimage.."magic/btn_battle_ability_glacial_wave1.png"
picBtnBattleAbilityGoddessMiracle1  		    = folderffbeimage.."magic/btn_battle_ability_goddess_miracle1.png"
picBtnBattleAbilityGoddessRevelation2           = folderffbeimage.."magic/btn_battle_ability_goddess_revelation2.png"
picBtnBattleAbilityGrapeshot1       		    = folderffbeimage.."magic/btn_battle_ability_grapeshot1.png"
picBtnBattleAbilityGrapeshot2       		    = folderffbeimage.."magic/btn_battle_ability_grapeshot2.png"
picBtnBattleAbilityGroundWork1       		    = folderffbeimage.."magic/btn_battle_ability_ground_work1.png"
picBtnBattleAbilityHeatedRounds2    		    = folderffbeimage.."magic/btn_battle_ability_heated_rounds2.png"
picBtnBattleAbilityHeartblaze2      		    = folderffbeimage.."magic/btn_battle_ability_heart_blaze2.png"
picBtnBattleAbilityHeavensFury2     		    = folderffbeimage.."magic/btn_battle_ability_heavens_fury2.png"
picBtnBattleAbilityHeroCrest1       		    = folderffbeimage.."magic/btn_battle_ability_hero_crest1.png"
picBtnBattleAbilityHyperdrive2      		    = folderffbeimage.."magic/btn_battle_ability_hyperdrive2.png"
picBtnBattleAbilityImperil1         		    = folderffbeimage.."magic/btn_battle_ability_imperil1.png"
picBtnBattleAbilityImperil2         		    = folderffbeimage.."magic/btn_battle_ability_imperil2.png"
picBtnBattleAbilityImpenetrableStance1          = folderffbeimage.."magic/btn_battle_ability_impenetrable_stance1.png"
picBtnBattleAbilityJudgmentBlade2               = folderffbeimage.."magic/btn_battle_ability_judgment_blade2.png"
picBtnBattleAbilityLastFootstep1    		    = folderffbeimage.."magic/btn_battle_ability_last_footstep1.png"
picBtnBattleAbilityLeadership1      		    = folderffbeimage.."magic/btn_battle_ability_leadership1.png"
picBtnBattleAbilityLiberatingFlash2 		    = folderffbeimage.."magic/btn_battle_ability_liberating_flash2.png"
picBtnBattleAbilityLightningBreath1 		    = folderffbeimage.."magic/btn_battle_ability_lightning_breath1.png"
picBtnBattleAbilityLightningStab1   		    = folderffbeimage.."magic/btn_battle_ability_lightning_stab1.png"
picBtnBattleAbilityMentalBreak1     		    = folderffbeimage.."magic/btn_battle_ability_mental_break1.png"
picBtnBattleAbilityMagazineBlast2       	    = folderffbeimage.."magic/btn_battle_ability_magazine_blast2.png"
picBtnBattleAbilityMagicalActivation1   	    = folderffbeimage.."magic/btn_battle_ability_magical_activation1.png"
picBtnBattleAbilityMultitask1           	    = folderffbeimage.."magic/btn_battle_ability_multitask1.png"
picBtnBattleAbilityMoxieAtk1        		    = folderffbeimage.."magic/btn_battle_ability_moxie_atk1.png"
picBtnBattleAbilityNapalmGrenade2   		    = folderffbeimage.."magic/btn_battle_ability_napalm_grenade2.png"
picBtnBattleAbilityNorthswainsGlow1 		    = folderffbeimage.."magic/btn_battle_ability_northswains_glow1.png"
picBtnBattleAbilityNorthswainsGlow2 		    = folderffbeimage.."magic/btn_battle_ability_northswains_glow2.png"
picBtnBattleAbilityPatrioticSlash1              = folderffbeimage.."magic/btn_battle_ability_patriotic_slash1.png"
picBtnBattleAbilityPatrioticSlash2              = folderffbeimage.."magic/btn_battle_ability_patriotic_slash2.png"
picBtnBattleAbilityPiledriver2   		        = folderffbeimage.."magic/btn_battle_ability_piledriver2.png"
picBtnBattleAbilityPresenceOfMind2  		    = folderffbeimage.."magic/btn_battle_ability_presence_of_mind2.png"
picBtnBattleAbilityPrismHeal2                   = folderffbeimage.."magic/btn_battle_ability_prism_heal2.png"
picBtnBattleAbilityPrismHeart2                  = folderffbeimage.."magic/btn_battle_ability_prism_heart2.png"
picBtnBattleAbilityPrismaticFlash1  		    = folderffbeimage.."magic/btn_battle_ability_prismatic_flash1.png"
picBtnBattleAbilityPrismaticFlash2  		    = folderffbeimage.."magic/btn_battle_ability_prismatic_flash2.png"
picBtnBattleAbilityProvoke2                     = folderffbeimage.."magic/btn_battle_ability_provoke2.png"
picBtnBattleAbilityRainbowVeil1                 = folderffbeimage.."magic/btn_battle_ability_rainbow_veil1.png"
picBtnBattleAbilityRashImpulse1                 = folderffbeimage.."magic/btn_battle_ability_rash_impulse1.png"
picBtnBattleAbilityRapidFire2                   = folderffbeimage.."magic/btn_battle_ability_rapid_fire2.png"
picBtnBattleAbilityRecoveryOil1                 = folderffbeimage.."magic/btn_battle_ability_recovery_oil1.png"
picBtnBattleAbilityRedCard2                     = folderffbeimage.."magic/btn_battle_ability_red_card2.png"
picBtnBattleAbilityRefreshingTool2              = folderffbeimage.."magic/btn_battle_ability_refreshing_tool2.png"
picBtnBattleAbilityRejuvenate1                  = folderffbeimage.."magic/btn_battle_ability_rejuvenate1.png"
picBtnBattleAbilityResistStop1                  = folderffbeimage.."magic/btn_battle_ability_resist_stop1.png"
picBtnBattleAbilityRoyalObligation1             = folderffbeimage.."magic/btn_battle_ability_royal_obligation1.png"
picBtnBattleAbilityRune1                        = folderffbeimage.."magic/btn_battle_ability_rune1.png"
picBtnBattleAbilityRuinousCleave1               = folderffbeimage.."magic/btn_battle_ability_ruinous_cleave1.png"
picBtnBattleAbilitySacredStrike2                = folderffbeimage.."magic/btn_battle_ability_sacred_strike2.png"
picBtnBattleAbilitySchwertDance1                = folderffbeimage.."magic/btn_battle_ability_schwert_dance1.png"
picBtnBattleAbilityShatteringShot1  		    = folderffbeimage.."magic/btn_battle_ability_shattering_shot1.png"
picBtnBattleAbilityShatteringShot2  		    = folderffbeimage.."magic/btn_battle_ability_shattering_shot2.png"
picBtnBattleAbilitySnowpetal1                   = folderffbeimage.."magic/btn_battle_ability_snowpetal1.png"
picBtnBattleAbilityStaticGuard1                 = folderffbeimage.."magic/btn_battle_ability_static_guard1.png"
picBtnBattleAbilitySteel1          		        = folderffbeimage.."magic/btn_battle_ability_steel1.png"
picBtnBattleAbilityTrueShot1        		    = folderffbeimage.."magic/btn_battle_ability_true_shot1.png"
picBtnBattleAbilityTrueShot2        		    = folderffbeimage.."magic/btn_battle_ability_true_shot2.png"
picBtnBattleAbilityUndermine1       		    = folderffbeimage.."magic/btn_battle_ability_undermine1.png"
picBtnBattleAbilityWaylay1                      = folderffbeimage.."magic/btn_battle_ability_waylay1.png"
picBtnBattleAbilityWaylay2                      = folderffbeimage.."magic/btn_battle_ability_waylay2.png"
picBtnBattleAbilityWickedLight2      		    = folderffbeimage.."magic/btn_battle_ability_wicked_light2.png"
picBtnBattleAbilityWordOfLaw1        		    = folderffbeimage.."magic/btn_battle_ability_word_of_law1.png"



picBtnBattleMagicAeroBlitz                      = folderffbeimage.."magic/btn_battle_magic_aero_blitz.png"
picBtnBattleMagicAeroga2        		        = folderffbeimage.."magic/btn_battle_magic_aeroga2.png"
picBtnBattleMagicAerora2        		        = folderffbeimage.."magic/btn_battle_magic_aerora2.png"
picBtnBattleMagicAreaBlast                      = folderffbeimage.."magic/btn_battle_magic_area_blast.png"
picBtnBattleMagicBiora1                         = folderffbeimage.."magic/btn_battle_magic_biora1.png"
picBtnBattleMagicBlizzaga1       		        = folderffbeimage.."magic/btn_battle_magic_blizzaga1.png"
picBtnBattleMagicChaosWaveZero2                 = folderffbeimage.."magic/btn_battle_magic_chaos_wave_zero_2.png"
picBtnBattleMagicChaosWave2                     = folderffbeimage.."magic/btn_battle_magic_chaos_wave2.png"
picBtnBattleMagicCrushingBlow                   = folderffbeimage.."magic/btn_battle_magic_crushing_blow.png"
picBtnBattleMagicCura           		        = folderffbeimage.."magic/btn_battle_magic_cura.png"
picBtnBattleMagicCuraja         		        = folderffbeimage.."magic/btn_battle_magic_curaja.png"
picBtnBattleMagicCuraja2        		        = folderffbeimage.."magic/btn_battle_magic_curaja2.png"
picBtnBattleMagicDeprotect1                     = folderffbeimage.."magic/btn_battle_magic_deprotect1.png"
picBtnBattleMagicDeprotect2                     = folderffbeimage.."magic/btn_battle_magic_deprotect2.png"
picBtnBattleMagicDeshell2                       = folderffbeimage.."magic/btn_battle_magic_deshell2.png"
picBtnBattleMagicElectricBlitz                  = folderffbeimage.."magic/btn_battle_magic_electric_blitz.png"
picBtnBattleMagicFira2            	            = folderffbeimage.."magic/btn_battle_magic_fira2.png"
picBtnBattleMagicFiraga2           		        = folderffbeimage.."magic/btn_battle_magic_firaga2.png"
picBtnBattleMagicHeatBlitz                      = folderffbeimage.."magic/btn_battle_magic_heat_blitz.png"
picBtnBattleMagicIceBlitz                       = folderffbeimage.."magic/btn_battle_magic_ice_blitz.png"
picBtnBattleMagicMeteor2         		        = folderffbeimage.."magic/btn_battle_magic_meteor2.png"
picBtnBattleMagicOsmose1         		        = folderffbeimage.."magic/btn_battle_magic_osmose1.png"
picBtnBattleMagicOsmose2         		        = folderffbeimage.."magic/btn_battle_magic_osmose2.png"
picBtnBattleMagicProtectga2      		        = folderffbeimage.."magic/btn_battle_magic_protectga2.png"
picBtnBattleMagicShellga1        		        = folderffbeimage.."magic/btn_battle_magic_shellga1.png"
picBtnBattleMagicStarfall                       = folderffbeimage.."magic/btn_battle_magic_starfall.png"
picBtnBattleMagicThundaga2         		        = folderffbeimage.."magic/btn_battle_magic_thundaga2.png"
picBtnBattleMagicThundaja1         		        = folderffbeimage.."magic/btn_battle_magic_thundaja1.png"
picBtnBattleMagicThundara1         		        = folderffbeimage.."magic/btn_battle_magic_thundara1.png"
picBtnBattleMagicThundara2         		        = folderffbeimage.."magic/btn_battle_magic_thundara2.png"
picBtnBattleMagicTimeStopper                    = folderffbeimage.."magic/btn_battle_magic_time_stopper.png"
picBtnBattleMagicUltima1                        = folderffbeimage.."magic/btn_battle_magic_ultima1.png"



picBtnBattleEvokeEarthenWall          		    = folderffbeimage.."magic/btn_battle_evoke_earthen_wall.png"
picBtnBattleEvokeHellfire             		    = folderffbeimage.."magic/btn_battle_evoke_hellfire.png"
picBtnBattleEvokeJudgmentBolt         		    = folderffbeimage.."magic/btn_battle_evoke_judgment_bolt.png"
picBtnBattleEvokeLunaticVoice         		    = folderffbeimage.."magic/btn_battle_evoke_lunatic_voice.png"
picBtnBattleEvokeRubyLight            		    = folderffbeimage.."magic/btn_battle_evoke_ruby_light.png"


