--
-- Created by IntelliJ IDEA.
-- User: denny
-- Date: 2/20/2017
-- Time: 10:32 PM
-- To change this template use File | Settings | File Templates.
--

FormCreate(varFormNameMainHomeQuest)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMainHomeQuestTop)

FormCreate(varFormNameMainHomeDailyQuestReward)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMainHomeDailyQuestTop)
FormAddCriteria2Do(varCriteriaExists, picBtnMainHomeDailyQuestReward)

FormCreate(varFormNameMainHomeDailyQuestNoReward)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaNotExists, picBtnMainHomeDailyQuestReward)
FormAddCriteria2Do(varCriteriaExists, critMainHomeDailyQuestTop)

FormCreate(varFormNameMainHomeDailyQuestClaimReward)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaNotExists, critMainHomeDailyQuestClaimComplete)
FormAddCriteria2Do(varCriteriaExists, critMainHomeDailyQuestClaimObjective)
FormAddCriteria2Do(varCriteriaExists, critMainHomeDailyQuestClaimRewards)

FormCreate(varFormNameMainHomeDailyQuestClaimComplete)
FormAddCriteria2Do(varCriteriaNotExists, critMainBottom)
FormAddCriteria2Do(varCriteriaExists, critMainHomeDailyQuestClaimObjective)
FormAddCriteria2Do(varCriteriaExists, critMainHomeDailyQuestClaimRewards)
FormAddCriteria2Do(varCriteriaExists, critMainHomeDailyQuestClaimComplete)

FormCreate(varFormNameMainDailyQuestCompleted)
FormAddCriteria2Do(varCriteriaNotExists, critQuestDailyCompletedRewardClaimed)
FormAddCriteria2Do(varCriteriaExists, critQuestDailyCompleted)

FormCreate(varFormNameMainDailyQuestCompletedClaimed)
FormAddCriteria2Do(varCriteriaExists, critQuestDailyCompleted)
FormAddCriteria2Do(varCriteriaExists, critQuestDailyCompletedRewardClaimed)


