--
-- Created by IntelliJ IDEA.
-- User: denny
-- Date: 4/17/2017
-- Time: 11:09 PM
-- To change this template use File | Settings | File Templates.
--

dofile(scriptPath()..parentfolder..parentsubfol..eventfolder.."config_action_detail.lua")

ActionOnForm(varFormNameMainArenaPvpRechargeEnergy)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnMainArenaColosseumRechargeEnergyNo)
ActionExec(varActionExecuteDoSetActionNextAction)
ActionExecVar("")
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnStdBack)
ActionExec(varActionExecuteDoWait)
ActionExecVar(1)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnStdBack)
ActionExec(varActionExecuteDoWait)
ActionExecVar(1)

ActionOnForm(varFormNameMainArena)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnMainHomeArenaSetup)
ActionExecWaitForm(varFormNameMainArenaRules)

ActionOnForm(varFormNameMainArenaRules)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnMainHomeArenaRulesOk)
ActionExecWaitForm(varFormNameMainArenaRulesSelectOpp)

ActionOnForm(varFormNameMainArenaRulesSelectOppConf)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnMainHomeArenaRulesSelectOppConfYes)
ActionExecWaitForm(varFormNameMainArenaRulesSelectOppConfBegin)

ActionOnForm(varFormNameMainArenaRulesSelectOppConfBegin)
ActionExec(varActionExecuteDoCounterInc)
ActionExecVar(1)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnMainHomeArenaRulesSelectOppConfBeginBegin)
ActionExec(varActionExecuteDoResetRoundExecute)
ActionExecVar("")
ActionExecWaitForm(varFormNameMainBattleEngaged)

ActionOnForm(varFormNameMainBattleResultArenaWon1)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(critBattleResultArenaWonTop)
ActionExecWaitForm(varFormNameMainBattleResultArenaWon2)

ActionOnForm(varFormNameMainBattleResultArenaWon2)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnBattleResultArenaOk)
ActionExecWaitForm(varFormNameMainBattleResultArenaRankUp)

ActionOnForm(varFormNameMainBattleResultArenaLost1)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(critBattleResultArenaLostTop)
ActionExecWaitForm(varFormNameMainBattleResultArenaLost2)

ActionOnForm(varFormNameMainBattleResultArenaLost2)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnBattleResultArenaOk)
ActionExecWaitForm(varFormNameMainBattleResultArenaRankUp)

ActionOnForm(varFormNameMainBattleResultArenaRankUp)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnBattleResultArenaOk)
ActionExecWaitForm(varFormNameMainBattleResultArenaWonRewards)

ActionOnForm(varFormNameMainBattleResultArenaWonRewards)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnBattleResultArenaRewardsOk)
ActionExecWaitForm(varFormNameMainArena)

ActionOnForm(varFormNameMainBattleResultArenaLostRewards)
ActionExec(varActionExecuteDoClickButton)
ActionExecVar(picBtnBattleResultArenaRewardsOk)
ActionExecWaitForm(varFormNameMainArena)



dofile(folderffbescript.."config_action_defs.lua")
dofile(folderffbescript.."config_action_defs_arena.lua")
dofile(folderffbescript.."config_action_defs_battle.lua")


